title: LibreTime Radio Automation
description: An open source radio automation server made for (and made by) low-power FM stations and the rest of us.
logo: 144px.png
show_downloads: false

layouts_dir: _layouts
data_dir: _data

favicon:

# For splash page layout only
headimage: img/header.jpg
headtext: Open Source Radio Automation
headsubtext: Everything you need to get your terrestrial / on-line radio station up and broadcasting like a pro - without breaking the bank! 
headbuttonurl: https://libretime.org
headbuttontext: Get LibreTime

# Build settings
plugins:
  - jekyll-feed
