title: LibreTime Radio Automation
description: An open source radio automation solutions made for (and made by) low-power FM stations and the rest of us.
logo: 144px.png
show_downloads: false

theme: jekyll-theme-minimal
layouts_dir: _layouts
data_dir: _data

navigation:
- text: Quick Install
  url: quickstart
- text: Features
  url: features
- text: FAQ
  url: faq
- text: Manual
  url: manual
- text: Help!
  url: troubleshooting