title: LibreTime 
description: An open source radio automation server made for (and by) low-power FM stations and the rest of us.
logo: 144px.png
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

layouts_dir: _layouts
includes_dir: _includes

favicon: favicon.ico

# For splash page layout only
headimage: img/header.jpg
headtext: Open Source Radio Automation
headsubtext: Everything you need to get your terrestrial / on-line radio station up and broadcasting like a pro - without breaking the bank! 
# items below - only for first front page link
headbuttonurl: index#get-started
headbuttontext: Get LibreTime

# Build settings
plugins:
  - kramdown

# Navigation
docsdrop:
- page: Broadcasting Live
  url: live-broadcast
- page: Intelligent Library
  url: library
- page: Playout History
  url: analytics
- page: Scheduling Shows
  url: scheduling-shows
- page: Troubleshooting
  url: troubleshooting
  
admindocsdrop:
- page: Admin Guides
  url: guides

topnav:
- page: Github
  url: https://github.com/LibreTime/libretime
- page: <svg class="bi bi-heart-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/></svg> Sponsor
  url: https://opencollective.com/libretime