title: LibreTime Radio Automation
description: An open source radio automation solutions made for (and made by) low-power FM stations and the rest of us.
logo: 144px.png
show_downloads: true

theme: jekyll-theme-minimal
layouts_dir: _layouts
data_dir: _data

navigation:
- text: Install
  url: install
- text: Features
  url: features
- text: FAQ
  url: faq
- text: Tutorials
  url: tutorials
- text: Appendix
  url: appendix
- text: Help!
  url: troubleshooting